name: publish

on:
  push:
    branches: main

jobs:
  # Build job
  # build:

  #   # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  #   permissions:
  #     pages: write # to deploy to Pages
  #     id-token: write # to verify the deployment originates from an appropriate source

  #   # Specify runner + deployment step
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1
  #     - name: set version
  #       run: echo "PROJECT_NUMBER = `git describe --tags`" >> Doxyfile
  #     - name: Generate Documentation
  #       uses: mattnotmitt/doxygen-action@edge

  # Deploy job
  deploy:
    # Add a dependency to the build job
    # needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions: write-all

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
      - name: set version
        run: echo "PROJECT_NUMBER = `git describe --tags`" >> Doxyfile
      - name: Generate Documentation
        uses: mattnotmitt/doxygen-action@edge
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html
          token: ${{ secrets.GITHUB_TOKEN }}
